FROM teste-jenkins

WORKDIR /app

# Copia apenas os arquivos de dependência primeiro (cache)
COPY package*.json ./

RUN npm ci

# Copia o restante do projeto
COPY . .

# Playwright já vem instalado nessa imagem,
# esse comando é opcional, mas seguro
RUN npx playwright install --with-deps

CMD ["npx", "playwright", "test"]
